---

name: Test Dispatch (receive)

on:
  push:
  workflow_dispatch:
    inputs:
      reason:
        required: true
        description: 'Reason for running this workflow'

jobs:
  test:
    name: Workflow Dispatch
    # only run this step if workflow dispatch triggered
    # log the reason the workflow dispatch was triggered
    if: |
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.reason != ''
    runs-on: ubuntu-latest
    steps:
      - env:
          INPUTS_REASON: ${{ github.event.inputs.reason }}
        run: |
          echo "Workflow dispatch reason: $INPUTS_REASON"
